update remote link to registry.cern.ch and add -cache argument for cacheing to sif file

diff --git a/cvmfs2go b/cvmfs2go
--- a/cvmfs2go
+++ b/cvmfs2go
@@ -10,7 +10,7 @@ export CVMFS2GO_CONF="${CVMFS2GO_CONF:-${CVMFS2GO_CONFIG_DIR}/default.local}"
 export CVMFS2GO_MOUNT_DIR="${CVMFS2GO_MOUNT_DIR:-${CVMFS2GO_BASE_DIR}/mount}"
 export CVMFS2GO_IMAGE_DIR="${CVMFS2GO_IMAGE_DIR:-${CVMFS2GO_BASE_DIR}/images}"
 
-export CVMFS2GO_IMG="${CVMFS2GO_IMG:-shub://adriansev/el7cvmfs.sing}" # Specify the location of Singularity image
+export CVMFS2GO_IMG="${CVMFS2GO_IMG:-oras://registry.cern.ch/asevcenc/el7cvmfs:latest}" # Specify the location of Singularity image
 
 export SINGULARITYENV_PS1='\[\033[1;31m\]${SINGULARITY_NAME}#\[\033[1;32m\][\D{%A %d.%m.%y %H:%M}] \u@\h : \[\033[1;34m\]\w \[\033[00m\]\n'
 export SINGULARITYENV_HOSTPWD="${PWD}"
@@ -52,9 +52,10 @@ Argument list:
 -clean|-cleanup|cleanup           : delete contents of cvmfs private cache -> ${CVMFS2GO_CACHE}
 -cleanimg|-cleanupimg|cleanupimg  : delete contents of containers local cache -> ${CVMFS2GO_IMAGE_DIR}
 -getdefaultconf|getdefaultconf    : for private mounting initialize the cvmfs configuration with https://github.com/adriansev/el7cvmfs.dock/tree/master/etc_cvmfs
--conf|conf                           : specify an alternative to CVMFS2GO_CONFIG_DIR/default.local; can be also specified by CVMFS2GO_CONF
--shell                             : instead of \"run\" use \"shell\" for singularity command
--exec                              : instead of \"run\" use \"exec\" for singularity command
+-conf|conf                        : specify an alternative to CVMFS2GO_CONFIG_DIR/default.local; can be also specified by CVMFS2GO_CONF
+-cache|cache                      : request cacheing of the remote image to a local sif image
+-shell                            : instead of \"run\" use \"shell\" for singularity command
+-exec                             : instead of \"run\" use \"exec\" for singularity command
 
 Singularity steering options:
 -e|--cleanenv
@@ -152,6 +153,10 @@ while [[ $# -gt 0 ]]; do
         shift # past argument
         shift # past value
         ;;
+        -cache|--cache|cache)
+        DO_CACHE="1"
+        shift
+        ;;
         -shell|--shell)
         [[ -z "${SET_ACTION}" ]] && { SING_ACTION="shell" ; SET_ACTION="1"; }
         shift
@@ -234,14 +239,13 @@ if [[ "${CWD}" == "${CWD##${USERHOME}}" ]]; then  # user home is not part of cwd
     CWD_MNT="$(df --output=target ${CWD} | tail -n +2)"  # let's bind mount the actual mount point of CWD
     SINGULARITY_BINDPATH="${SINGULARITY_BINDPATH}${SINGULARITY_BINDPATH:+,}${CWD_MNT}"
 fi
-
 export SINGULARITY_BINDPATH
 
-# it was stated that singularity cache is not suitable for concurent access; then let's cache it
-if [[ ! -e "${CVMFS2GO_IMG}" ]]; then # if not a local image
+# if explict local cache is requested
+if [[ -n "${DO_CACHE}" ]]; then
     LOCAL_NAME="${IMAGE_DIR}/$(basename ${CVMFS2GO_IMG} | sed 's/:/_/g').sif"
     if [[ ! -e "${LOCAL_NAME}" ]]; then
-        singularity pull --name ${LOCAL_NAME} ${CVMFS2GO_IMG} &> /dev/null && export CVMFS2GO_IMG="${LOCAL_NAME}" || { echo "Error caching ${CVMFS2GO_IMG}"; exit 1; }
+        singularity pull -F --name ${LOCAL_NAME} ${CVMFS2GO_IMG} &> /dev/null && export CVMFS2GO_IMG="${LOCAL_NAME}" || { echo "Error caching ${CVMFS2GO_IMG}"; exit 1; }
     fi
 fi
 
